services:

    #
    # Event Listeners
    #
    elcodi.event_listener.entity_translator_entity:
        class: %elcodi.event_listener.entity_translator_entity.class%
        lazy: true
        arguments:
            container: @service_container
            locale: @elcodi.locale
        tags:
            - { name: doctrine.event_listener, event: postLoad }
