services:

    #
    # Event Listeners
    #
    elcodi.core.entity_translator.event_listener.entity_translator_entity:
        class: %elcodi.core.entity_translator.event_listener.entity_translator_entity.class%
        arguments:
            container: @service_container
            locale: @elcodi.locale
        tags:
            - { name: doctrine.event_listener, event: postLoad }
