parameters:

    #
    # Factories
    #
    elcodi.factory.entity_translator.class: Elcodi\Component\EntityTranslator\Factory\EntityTranslatorFactory
    elcodi.factory.entity_translation.class: Elcodi\Component\EntityTranslator\Factory\EntityTranslationFactory

    #
    # Repositories
    #
    elcodi.repository.entity_translation.class: Elcodi\Component\EntityTranslator\Repository\EntityTranslationRepository

    #
    # Services
    #
    elcodi.services.cached_entity_translation_provider.class: Elcodi\Component\EntityTranslator\Services\CachedEntityTranslationProvider
    elcodi.services.entity_translation_provider.class: Elcodi\Component\EntityTranslator\Services\EntityTranslationProvider
    elcodi.entity_translator_builder.class: Elcodi\Component\EntityTranslator\Services\EntityTranslatorBuilder
    elcodi.entity_translator.class: Elcodi\Component\EntityTranslator\Services\EntityTranslator
    elcodi.entity_translator_changes.class: Elcodi\Component\EntityTranslator\Services\EntityTranslationChangesBag

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.entity_translator.class: Elcodi\Component\EntityTranslator\EventDispatcher\EntityTranslatorEventDispatcher

    #
    # Event Listeners
    #
    elcodi.event_listener.entity_translator_form.class: Elcodi\Component\EntityTranslator\EventListener\EntityTranslatorFormEventListener
    elcodi.event_listener.entity_translator_entity.class: Elcodi\Component\EntityTranslator\EventListener\EntityTranslatorEntityEventListener
