services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.entity_translator:
        class: %elcodi.event_dispatcher.entity_translator.class%
        arguments:
            - @event_dispatcher
