services:

    #
    # Event Dispatchers
    #
    elcodi.core.entity_translator.event_dispatcher.entity_translator:
        class: %elcodi.core.entity_translator.event_dispatcher.entity_translator.class%
        arguments:
            event_dispatcher: @event_dispatcher

    elcodi.entity_translator_event_dispatcher:
        alias: elcodi.core.entity_translator.event_dispatcher.entity_translator
