services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.entity_translator:
        class: %elcodi.core.entity_translator.event_dispatcher.entity_translator.class%
        arguments:
            event_dispatcher: @event_dispatcher
