services:

    #
    # Factories
    #

    #
    # Factory for entity tax
    #
    elcodi.factory.entity_translation:
        class: %elcodi.factory.entity_translation.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.entity_translation.class%"]]

    #
    # Factory for Translator service
    #
    elcodi.factory.entity_translator:
        class: %elcodi.factory.entity_translator.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity_translator.class%"]]
