services:

    #
    # Object Managers
    #
    elcodi.object_manager.entity_translation:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.entity_translator.entity.entity_translation.class% ]
