services:

    #
    # Object Managers
    #
    elcodi.object_manager.entity_translation:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.entity_translator.entity.entity_translation.class%
