services:

    #
    # Repositories
    #

    #
    # Repository for entity translation
    #
    elcodi.repository.entity_translation:
        parent: elcodi.abstract_repository
        class: %elcodi.repository.entity_translation.class%
        arguments: [ %elcodi.entity.entity_translation.class% ]
